GitHub: Improved CI
octokit/octokit.graphql.net pull request #326
Opened 2024-09-19 20:30 UTC by 0x5bfa

### Before the change?

* Deleted unnecessary CIs
  * add_to_octokit_project.yml
  * generate-schema.yml
  * integration-tests.yml
* Improved the main CI (including fixes)
* Merged auto add to the project and auto comment Actions

### After the change?

* 

### Pull request checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

- No

2024-09-20 06:55 UTC, Lamparter requested changes
Here are a few suggestions 😄

@0x5bfa while you're at it, would you mind changing the PR title to "GitHub: Improve CI" or something like that?

2024-09-20 06:55 UTC, Lamparter commented on .github/workflows/ci.yml
> +        shell: bash
@0x5bfa why do these run on bash?

2024-09-20 06:55 UTC, Lamparter commented on .github/workflows/ci.yml
> +        shell: bash
..shouldn't it be PowerShell or something like that, considering that it's running on Windows anyway?

2024-09-20 06:55 UTC, Lamparter commented on .github/workflows/ci.yml
> +        shell: bash
Which leads me to ask, why does it run on Windows? Don't Windows runners cost more anyway?

2024-09-20 06:55 UTC, Lamparter commented on .github/workflows/generate-schema.yml
IMO this should be its _own_ CI runner event; unless you think otherwise.
It's not part of the CI really.

2024-09-20 06:55 UTC, Lamparter commented on .github/workflows/generate-schema.yml
> -      - main
If it's already publishing to NuGet, I don't really understand why this would be on push to main (theoretically, obviously you've just deleted it). It would be better to generate schema on PR/cronjob and make it a required check.

2024-09-20 06:55 UTC, Lamparter commented on .github/workflows/auto-response.yml
> +    types: [reopened, opened]
Why does it run on reopened?
```suggestion
    types: opened
```

2024-09-20 06:55 UTC, Lamparter commented on .github/workflows/auto-response.yml
> +    types: [reopened, opened]
...it wouldn't need to re-add to the project? That would surely be useless...?
```suggestion
    types: opened
```

2024-09-20 06:55 UTC, Lamparter commented on .github/workflows/auto-response.yml
> +      - name: Get the issue or PR number
What's the point of this change?
```suggestion
      - name: Determine issue or PR number
```

2024-09-20 06:55 UTC, Lamparter commented on .github/workflows/auto-response.yml
> +          labeled: "Status: Stale"
If it's going to be added _back_ to the project on reopen, surely you should attach a field for which project status it's going to be in, like "in progress"

2024-09-20 07:46 UTC, 0x5bfa commented on .github/workflows/generate-schema.yml
> -      - main
Yes. I really couldn't understand.
This just "tests" the generator, it doesn't update models to the main branch.

2024-09-20 07:47 UTC, 0x5bfa commented on .github/workflows/generate-schema.yml
I'll create a CI to update the model into the main branch.
It'd create a PR something like dependabot's PR when a new scheme is up for.

2024-09-20 07:49 UTC, 0x5bfa commented on .github/workflows/ci.yml
> +        shell: bash
> cost

This project is platform-independent so I think you can use Ubuntu runner. That's said, you don't have to pay for anything even though you use windows runner.

> shouldn't it be PowerShell

Idk, I just reverted to the before state. It used to have used bash and worked well.

2024-09-20 07:51 UTC, 0x5bfa commented on .github/workflows/auto-response.yml
> +    types: [reopened, opened]
I merged adding to project task into this ci file. It has to be run when reopened too. I added condition to adding auto comment not to run when reopened.

2024-09-20 07:51 UTC, 0x5bfa commented on .github/workflows/auto-response.yml
> +    types: [reopened, opened]
As above.

2024-09-20 07:53 UTC, 0x5bfa commented on .github/workflows/auto-response.yml
> +          labeled: "Status: Stale"
I prefer to make behavior changes after asking the maintainer in this area.
@nickfloyd What's your thoughts on this?

2024-09-20 14:43 UTC, Lamparter commented on .github/workflows/generate-schema.yml
> -      - main
...what.. that's very strange useless CI...

2024-09-20 14:43 UTC, Lamparter commented on .github/workflows/generate-schema.yml
That's a good idea.

2024-09-20 14:46 UTC, Lamparter commented on .github/workflows/ci.yml
> +        shell: bash
I know it does cost more, but organisations are provisioned with credits/runner times, of which windows runners cost more. Obviously, this is a GitHub/Microsoft org and it doesn't cost the department any "money" apart from their internal budget. I'm pretty much just thinking of from a power-efficiency point of view.

2024-09-24 15:31 UTC, nickfloyd requested changes
Hey y'all,  

Thanks again for the improvements.  I have a few comments for clarity.  Please let me know if you have any questions.

2024-09-24 15:31 UTC, nickfloyd commented on .github/workflows/auto-response.yml
> +    types: [reopened, opened]
See my comment above about changing the template in the org repo

2024-09-24 15:31 UTC, nickfloyd commented on .github/workflows/ci.yml
> +        shell: bash
I alluded to this above but between @kfcampbell and me we own over 80 repos in this organization, so where ever we have the flexibility to run ubuntu (as a factor of standardization) that is preferred.  We cover about 9 different languages in a multitude of environments.  So while it seems natural to target languages and platforms in a repo like this, the bigger picture for the community as a whole is to be less esoteric per repo.  Let me know if that makes sense.

2024-09-24 15:31 UTC, nickfloyd commented on .github/workflows/generate-schema.yml
100% that would be perfect and generally what was originally intended. The generator, due to tree walking and other things, can be a bit unstable. So having it produce it's own PR on success would be ideal.

2024-09-24 15:31 UTC, nickfloyd commented on .github/workflows/integration-tests.yml
I'd prefer that both the unit and integration tests run on PR create / update and merge - this was disabled due to some instabilities but it would be nice to see this reinstated.

2024-09-25 07:46 UTC, 0x5bfa commented on .github/workflows/ci.yml
> +        shell: bash
Totally makes sense, if I'm not wrong this works on all platforms that are covered by .NET
I'll try to build this workflow within Ubuntu environment.

2024-09-25 07:49 UTC, 0x5bfa commented
TODO: make change in .github repo too.

2024-09-25 09:58 UTC, 0x5bfa commented on .github/workflows/ci.yml
> +        shell: bash
Now, CI successfully works on Ubuntu.

2024-09-25 10:00 UTC, 0x5bfa commented on .github/workflows/integration-tests.yml
How about creating the job in the main CI?

The jobs are:
- build
- unit-tests
- integration-tests
- pack

2024-09-25 18:05 UTC, Lamparter commented
@0x5bfa FYI
https://github.com/RiversideValley/Octokit-CommunityHealth

2024-09-27 02:47 UTC, 0x5bfa commented on .github/workflows/integration-tests.yml
Got it. Now the CI runs integration tests too and I separated jobs for each purpose. Please check out and let me know what you think 👍

2024-09-27 15:34 UTC, nickfloyd commented
The ci.yml changes look great... the only thing remaining is to rollback the changes made to immediate-response / auto-response.

2024-09-28 06:20 UTC, 0x5bfa commented
All clear, up for merge.
We'll make changes in .github repo shortly.

2024-10-07 18:38 UTC, nickfloyd approved these changes

2024-10-07 18:38 UTC, merged

2024-10-07 18:41 UTC, nickfloyd commented
> Btw what's [configure-integration-tests.ps1](https://github.com/octokit/octokit.graphql.net/blob/main/scripts/configure-integration-tests.ps1) for?

Great question.  I couldn't tell you with 100% certainty but from what I remember this was a sort of primer to establish a local environment for running tests.  

Candidly, I feel like a README on running tests would serve us all in a much better way, platform independent, tooling independent, and all that...

2024-10-07 20:45 UTC, Lamparter commented
The CI badge in the README is broken 😅
Posting a quick fix now